version: '3'
services:
  postgres:
    image: postgres
    networks:
    - impala-nw
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
  impala:
    build: .
    cap_add:
      - SYS_TIME
    image: ibisproject/impala
    hostname: localhost
    networks:
    - impala-nw
    external_links:
    - postgres
    environment:
      PGPASSWORD: postgres
    ports:
    # HDFS
    - 9020:9020
    - 50070:50070
    - 50075:50075
    - 8020:8020
    - 8042:8042
    # Hive
    - 9083:9083
    # Impala
    - 21000:21000
    - 21050:21050
    - 25000:25000
    - 25010:25010
    - 25020:25020
  kudu-master:
    build:
      context: .
      dockerfile: Dockerfile
    image: parrotstream/kudu:latest
    networks:
      impala-nw:
        aliases:
        - kudu
    cap_add:
    - SYS_TIME
    ports:
    - 7051:7051
    - 8051:8051
    environment:
      KUDU_MASTER: "true"
  kudu-tserver:
    build:
      context: .
      dockerfile: Dockerfile
    image: parrotstream/kudu:latest
    networks:
    - impala-nw
    cap_add:
    - SYS_TIME
    ports:
    - 7050:7050
    - 8050:8050
    environment:
      KUDU_MASTER: "false"

networks:
  default:
    external:
      name: impala-nw
  impala-nw:
    driver: bridge
